- hosts: web1
  tasks:
    - name: Tranfer template to web server
      template: # this is a model where it transfer files to a remote host(ie web1)
        src: table.j2
        dest: /var/www/html/index.php